### PR TITLE
Refactor and implement function for populating store catalogues

### PR DESCRIPTION
**Pull request by yousefamar**
(Again will only work after closing https://github.com/me-box/admin/issues/11)

### CODE REVIEW

**Comment by Toshbrown** [comment]
Hi,

 Looks good a couple of comments:

line 105 catalog.js "if (metadata.unit)" should it be "if (metadata.location)"

The naming of the notifications.js might become confusing. At some point, there will be a notification service. How about calling it dataNotifications or dataSubscriptions? 

We need some way to delay the start of the app/driver until all the datastores are ready.

**Comment by Toshbrown** [comment]
The notification service is a datbox platform component that is used by apps/drivers to send notifications (email,sms,push) to user of the databox.

I'm not sure its possable for the CM to know when a store is ready. At the moment the store is simple but we have used more complex stores , e.g influxDB, mysql in the past. These have varable startime depending on the data thay hold so it can get quite messy.

**Comment by yousefamar** [comment]
Which reminds me: should we make the `/status` thing official (or add something similar to specs)? That might be a step up from "just keep trying until your request gets a response".

It might come down to a trade-off between app/driver marginal complexity and install time if we e.g. just poll `/status` here before continuing for example: https://github.com/me-box/databox/blob/master/src/container-manager.js#L752

**Comment by Toshbrown** [comment]
Also just been looking at #11. Whats the blocker? and I will try and get it fixed.

The package stuff is for the SDK apps and is a hangover form mozfest. I'm not sure it will stay in its current form but need to have a chat with Tom to see where he is with it.

**Comment by Toshbrown** [comment]
Happy to force all things to have a /status its a bit neater than just wating for a sucsess on a random http request

**Comment by yousefamar** [comment]
Ah, I see. Makes sense ­— let's call WebSocket notification subscription events from now on, and those email/sms/push notifications.

> I'm not sure its possable for the CM to know when a store is ready.

I don't think apps/driver could do anything the CM cannot already do too to find out besides "query and see if it responds, if not, try again". Should we add a new store-side thing that fires a message once it's done init-ing? Otherwise polling `/status` could be enough and the CM could just hold off on launching drivers/apps until it gets the green light from their dependent stores.

> Also just been looking at #11. Whats the blocker? and I will try and get it fixed.

We did talk about some additional things on Skype, so to summarise:

- We need some way (field) to differentiate between read and write permissions (currently, this hack gives both: https://github.com/me-box/databox/pull/41/files#diff-bfdda56fc56293cc0ec7d8b722fe6dceR776) because current manifest specs assumes read/write is embedded in the URL which it isn't anymore.
- We established on Skype that drivers are given write permissions to their stores automatically, rather than repeating the SLA process on both sides of a store for every datasource. The CM needs to explicitly grant these permissions (in a similar way to the link above).
- Those listed SLA fields are unimplemented, so the CM doesn't know what permissions to grant. Fore v0.1, we only really need to know if a datasource is enabled, what it's URL is, and point 1. How the CM gets that info from the dashboard isn't super important, as long as it gets it (currently all those are undefined).
- Package environment variables are undefined because `.id` (https://github.com/me-box/databox/blob/master/src/container-manager.js#L799) is one of those things that isn't real (or a remnant of MozFest). So apps/drivers don't have the entirety of that information yet.

I think if we update the manifest specs with what we want and weed out old things, then everything else can fall into place.

**Comment by yousefamar** [comment]
So to actually answer your question, the blocker is that due to a combination of things:

- Apps/drivers don't get datasource urls as env vars, but even if they hardcoded them:
- Their requests to stores will be currently always be rejected because they're considered to have inadequate permissions. They're considered to have inadequate permissions because the CM doesn't tell the arbiter what it should grant. The CM doesn't tell the arbiter what it should grant, because the SLA the dashboard passes is missing things from the (outdated) specs, as far as I can tell.

P.S. I just renamed notifications :+1:

**Comment by Toshbrown** [comment]
> Apps/drivers don't get datasource urls as env vars, but even if they hard coded them:

Apps get the datasource information in the DATASOURCE_[clientid] environment variable where clientid is specified by the app in the datasources section of the manifest. This env var contains a copy of the hypercat item relating to the datasource. I think this is being set by the CM and is available to apps. 

> Their requests to stores will be currently always be rejected because they're considered to have inadequate permissions. They're considered to have inadequate permissions because the CM doesn't tell the arbiter what it should grant. The CM doesn't tell the arbiter what it should grant, because the SLA the dashboard passes is missing things from the (outdated) specs, as far as I can tell.

This is an issue I will look into adding these ASAP

**Comment by yousefamar** [comment]
I see, so the `PACKAGE` one is deprecated then? I'm not sure if I understand how the `DATASOURCE` one works either — shouldn't apps/drivers need info, but drivers are the one creating that info, so is that generated from the manifest (the way it's currently spec'd out) and sent beforehand?

I don't get those hypercat items; this is how the env vars look for my tests. I thought I may be doing something wrong in manifest to cause this which is why I called for an update, but it could be a different misconfiguration?

```
            "Env": [
                "DATABOX_IP=127.0.0.1",
                "DATABOX_LOCAL_NAME=databox-driver-template-node",
                "DATABOX_ARBITER_ENDPOINT=https://databox-arbiter:8080",
                "DATABOX_LOGSTORE_ENDPOINT=https://databox-logstore:8080/databox-driver-template-node",
                "DATABOX_DRIVER_TEMPLATE_NODE_DATABOX_STORE_BLOB_ENDPOINT=https://databox-driver-template-node-databox-store-blob:8080",
                "ARBITER_TOKEN=Y7RIqTfif5iIml/3yYQyEA221q3CYcmxz8Ell2ds2bs=",
                "CM_HTTPS_CA_ROOT_CERT=-----BEGIN CERTIFICATE-----\r\nBLABLABLA\r\n-----END CERTIFICATE-----\r\n",
                "HTTPS_SERVER_PRIVATE_KEY=-----BEGIN CERTIFICATE-----\r\nBLABLABLA\r\n-----END CERTIFICATE-----\r\n",
                "HTTPS_SERVER_CERT=-----BEGIN CERTIFICATE-----\r\nBLABLABLA\r\n-----END CERTIFICATE-----\r\n",
                "DATASOURCE_test=undefined",
                "PACKAGE_undefined=true",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NPM_CONFIG_LOGLEVEL=info",
                "NODE_VERSION=7.2.1"
            ],
```

**Comment by Toshbrown** [comment]
DATASOURCE os only for apps, drivers can name their sources however they want ;-)

**Comment by yousefamar** [comment]
Ahh, I see. So driver writes to store catalogue, user goes through SLA with an app that wants those things, CM reads from catalogues and launches the app with those items as env var. Drivers get a wildcard permissions to write to their stores automatically, and they already know the store hostnames because they named it themselves as a dependency in manifest. Neat!

**Comment by Toshbrown** [comment]
One minor update both drivers and apps are granted write permissions to any store new request in their manifest.

**Comment by Toshbrown** [comment]
Hi Yousef, 

I've been thinking about this:

>It might come down to a trade-off between app/driver marginal complexity and install time if we e.g. just poll /status here before continuing for example: https://github.com/me-box/databox/blob/master/src/container-manager.js#L752

 If we handle waiting in the app/driver we can start the containers in parallel reducing app install time which can be quite large if we need to pull lots of new containers.

**Comment by Toshbrown** [comment]
@yousefamar I don't have write access so can't merge this.

**Comment by yousefamar** [comment]
Thanks for letting me know — I just gave Databox Team write access.

Agreed, parallel start is what I was thinking about too, but how much of a delay are we talking? We wouldn't launch unrelated containers in series, but only dependencies, so it seems to me like we'd only ever have 1 or 2 containers queued up to launch at a time.

Then, even though an app/driver has actually "launched" it would still be delaying itself until the dependencies all get an active status, moving the waiting part from CM to app/driver. So the times where it would actually make a difference is when app/driver init times are big. Is that worth shifting complexity to apps/drivers?

If so, then that would only affect people who don't use our libs (because they want to use a different language or whatever). In the Node lib I could add a new function that returns a `Promise` that resolves when all stores are active, and in the Java lib, a method that blocks until they are. How does that sound?

**Comment by yousefamar** [comment]
Oh and I forgot to add, pulling and creating can all still be triggered in parallel — just the "start" bit could be synchronous, but either way I'll add them in the libs for sanity's sake.

**Pull request merged**
